#!/usr/bin/env bash
# cmux post-create hook: pin this isolated worktree's Docker stack to the
# workspace's allotted CMUX_PORT range so parallel worktrees never collide on
# the host's published ports.
#
#   webui (Pizza Tracker) -> CMUX_PORT
#   temporal gRPC         -> CMUX_PORT + 1
#   temporal Web UI       -> CMUX_PORT + 2
#
# Compose auto-loads the generated compose.override.yaml; the `!override` tag
# replaces the base port mappings instead of appending to them. The file is
# gitignored and torn down with the stack by pre-destroy.sh.
set -euo pipefail

if [[ -z "${CMUX_PORT:-}" ]]; then
  echo "post-create: CMUX_PORT not set; leaving the default host ports in place."
  exit 0
fi

webui_port=$((CMUX_PORT))
temporal_grpc_port=$((CMUX_PORT + 1))
temporal_ui_port=$((CMUX_PORT + 2))
project_name="cmux-${CMUX_FEATURE_SLUG:-workspace}"

override="${CMUX_FEATURE_WORKTREE:-$PWD}/compose.override.yaml"
cat >"${override}" <<YAML
# Generated by .cmux/post-create.sh — do not edit, do not commit.
# Pins host-published ports to this cmux workspace's CMUX_PORT range so
# parallel worktrees don't collide on 8080 / 7233 / 8233.
name: ${project_name}

services:
  backend:
    ports: !override
      - "${webui_port}:8080" # Pizza Tracker http://localhost:${webui_port}

  temporal:
    ports: !override
      - "${temporal_grpc_port}:7233" # workers & clients gRPC
      - "${temporal_ui_port}:8233" # Web UI http://localhost:${temporal_ui_port}
YAML

echo "post-create: wrote ${override}"
echo "  Pizza Tracker : http://localhost:${webui_port}"
echo "  Temporal gRPC : localhost:${temporal_grpc_port}"
echo "  Temporal UI   : http://localhost:${temporal_ui_port}"
